@TodoApi_HostAddress = http://localhost:5083

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###



@id=1
PUT {{TodoApi_HostAddress}}/todoitems/{{id}}
Content-Type: application/json

{
  "id": 1,
  "name": "feed fish"
}

###

GET {{TodoApi_HostAddress}}/todoitems/{{id}}

###

PATCH {{TodoApi_HostAddress}}/todoitems/{{id}}
Content-Type: application/json

{
  "name": "test"
}

###
